name: Docker Nightly Release

on:
  push:
    branches: [ nightly ]
  pull_request:
    branches: [ nightly ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          ref: nightly

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            "BRANCH_NAME=nightly"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kometateam/kometa:nightly
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push lxml Version
        id: docker_build_lxml
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile.lxml
          build-args: |
            "BRANCH_NAME=nightly"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kometateam/kometa:lxml-nightly
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Send Discord Commit Notification
        uses: Kometa-Team/discord-notifications@master
        with:
          webhook_id_token: ${{ secrets.DEVELOP_WEBHOOK }}
          title: Commits
          message: "<@&967002147520675840> - An update to Kometa has now been published and is available to users of the **nightly** branch."
          commits: "true"
          username: Kobota
          avatar_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/.github/logo.png
          author: ${{ secrets.REPO_NAME }} Nightly Release
          author_icon_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/.github/release.png

      - name: Discord Success Notification
        uses: Kometa-Team/discord-notifications@master
        if: success()
        with:
          webhook_id_token: ${{ secrets.BUILD_WEBHOOK }}
          title: "${{ secrets.REPO_NAME }} nightly: **Build Successful**"
          url: https://github.com/Kometa-Team/${{ secrets.REPO_NAME }}/actions/runs/${{ github.run_id }}
          color: 844716
          username: Kobota
          avatar_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/.github/logo.png
          author: Docker
          author_icon_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/.github/docker.png

      - name: Discord Failure Notification
        uses: Kometa-Team/discord-notifications@master
        if: failure()
        with:
          webhook_id_token: ${{ secrets.BUILD_WEBHOOK }}
          message: <@&1079153184007790652>
          title: "${{ secrets.REPO_NAME }} nightly: **Build Failed**"
          url: https://github.com/Kometa-Team/${{ secrets.REPO_NAME }}/actions/runs/${{ github.run_id }}
          color: 14879811
          username: Kobota
          avatar_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/.github/logo.png
          author: Docker
          author_icon_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/.github/docker.png
