name: Validate Pull Request

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

jobs:

  validate-pull:
    runs-on: ubuntu-latest
    steps:

      - name: Display Refs
        run: |
          echo "Base Repo: ${{ github.event.pull_request.base.repo.full_name }}"
          echo "Base Ref: ${{ github.base_ref }}"
          echo "Head Repo: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Head Ref: ${{ github.event.pull_request.head.ref }}"

      - name: Check Base Branch
        if: github.base_ref == 'master' || github.base_ref == 'develop'
        run: |
          echo "ERROR: Pull Requests cannot be submitted to master or develop. Please submit the Pull Request to the nightly branch"
          exit 1

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.37.0

  docker-build-pull:
    runs-on: ubuntu-latest
    needs: [ validate-pull ]
    if: contains(github.event.pull_request.labels.*.name, 'docker') || contains(github.event.pull_request.labels.*.name, 'testers')
    outputs:
      commit-msg: ${{ steps.update-version.outputs.commit-msg }}
      version: ${{ steps.update-version.outputs.version }}
    steps:

      - name: Create App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Update VERSION File
        id: update-version
        run: |
            value=$(cat VERSION)
            old_msg=$(git log -1 HEAD --pretty=format:%s)
            echo "commit-msg=${old_msg}" >> $GITHUB_OUTPUT
            version="${value%-build*}"
      
            if [[ "$value" == *"-"* ]]; then
                value2="${value#*-build}"
                if [[ "$value2" == *"."* ]]; then
                    build_value="${value2%.*}"
                    part_value="$((${value2#*.} + 1))"
                else
                    build_value="${value#*-build}"
                    part_value="1"
                fi
            else
                build_value="0"
                part_value="1"
            fi
      
            new_value="${version}-build${build_value}.${part_value}"
            echo "version=${new_value}" >> $GITHUB_OUTPUT
      
            echo "$new_value" > "VERSION"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add VERSION
            git commit -m "Part: ${part_value}"
            git push

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            "BRANCH_NAME=${{ github.event.pull_request.head.ref }}"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kometateam/kometa:${{ github.event.pull_request.head.ref }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Discord Success Notification
        uses: Kometa-Team/discord-notifications@master
        if: success()
        with:
          webhook_id_token: ${{ secrets.BUILD_WEBHOOK }}
          title: "${{ vars.REPO_NAME }} ${{ github.event.pull_request.head.ref }}: ${{ vars.TEXT_SUCCESS }}"
          url: https://github.com/Kometa-Team/${{ vars.REPO_NAME }}/actions/runs/${{ github.run_id }}
          color: ${{ vars.COLOR_SUCCESS }}
          username: ${{ vars.BOT_NAME }}
          avatar_url: ${{ vars.BOT_IMAGE }}
          author: ${{ vars.DOCKER_NAME }}
          author_icon_url: ${{ vars.DOCKER_IMAGE }}

      - name: Discord Failure Notification
        uses: Kometa-Team/discord-notifications@master
        if: failure()
        with:
          webhook_id_token: ${{ secrets.BUILD_WEBHOOK }}
          message: ${{ vars.BUILD_FAILURE_ROLE }}
          title: "${{ vars.REPO_NAME }} ${{ github.event.pull_request.head.ref }}: ${{ vars.TEXT_FAILURE }}"
          url: https://github.com/Kometa-Team/${{ vars.REPO_NAME }}/actions/runs/${{ github.run_id }}
          color: ${{ vars.COLOR_FAILURE }}
          username: ${{ vars.BOT_NAME }}
          avatar_url: ${{ vars.BOT_IMAGE }}
          author: ${{ vars.DOCKER_NAME }}
          author_icon_url: ${{ vars.DOCKER_IMAGE }}

  notify-testers:
    runs-on: ubuntu-latest
    if: github.event.action == 'labeled' && github.event.label.name == 'tester'
    steps:

      - name: Get Description
        id: get-description
        run: |
          body="${{ github.event.pull_request.body }}"
          body=$(echo "$body" | sed -n '/## Description/,/## Issues Fixed or Closed/{/## Description/b;/## Issues Fixed or Closed/b;p}')
          body=$(echo $body|tr -d '\n')
          echo "description=$body" >> $GITHUB_OUTPUT

      - name: Discord Testers Notification
        uses: Kometa-Team/discord-notifications@master
        with:
          webhook_id_token: ${{ secrets.TESTERS_WEBHOOK }}
          message: "The Kometa team are requesting <@&917323027438510110> to assist with testing an upcoming feature/bug fix.

                    * For Local Git pull and checkout the `${{ github.event.pull_request.head.ref }}` branch 

                    * For Docker use the `kometateam/kometa:${{ github.event.pull_request.head.ref }}` image to do your testing

                    Please report back either here or on the original GitHub Pull Request"
          title: ${{ github.event.pull_request.title }}
          description: ${{ steps.get-description.outputs.description }}
          url: https://github.com/Kometa-Team/${{ vars.REPO_NAME }}/pull/${{ github.event.number }}
          color: ${{ vars.COLOR_SUCCESS }}
          username: ${{ vars.BOT_NAME }}
          avatar_url: ${{ vars.BOT_IMAGE }}
          author: ${{ vars.GIT_NAME }}
          author_icon_url: ${{ vars.GIT_IMAGE }}

  update-testers:
    runs-on: ubuntu-latest
    needs: [ docker-build-pull ]
    if: github.event.action == 'synchronize' && github.event.label.name == 'tester'
    steps:

      - name: Discord Testers Notification
        uses: Kometa-Team/discord-notifications@master
        with:
          webhook_id_token: ${{ secrets.TESTERS_WEBHOOK }}
          message: "New Commit Pushed to `${{ github.event.pull_request.head.ref }}`: ${{ needs.docker-build-pull.outputs.version }}"
          description: ${{ needs.docker-build-pull.outputs.commit-msg }}
          url: https://github.com/Kometa-Team/${{ vars.REPO_NAME }}/pull/${{ github.event.number }}
          color: ${{ vars.COLOR_SUCCESS }}
          username: ${{ vars.BOT_NAME }}
          avatar_url: ${{ vars.BOT_IMAGE }}
          author: ${{ vars.GIT_NAME }}
          author_icon_url: ${{ vars.GIT_IMAGE }}